### ISSUE TITLE
Design DB.

### ISSUE THREAD

**Issue by JAndresHJ** [IntersysConsulting/ingangsters-api#1]

**Comment by JAndresHJ** [comment]
@jogadev y @sofia-robles-Intersys Aquí esta el diagrama de la colección. Para abrirlo vayan a _https://www.draw.io/_ descomprimen el archivo y abren el .drawio

[Ecommerce_collection v3.zip](https://github.com/IntersysConsulting/ingangsters-api/files/3571736/Ecommerce_collection.v3.zip)

**Comment by martin-one** [comment]
Agregada etiqueta "shippable" a product.
[Ecommerce_collection v2.zip](https://github.com/IntersysConsulting/ingangsters-api/files/3535445/Ecommerce_collection.v2.zip)

**Comment by martin-one** [comment]
Agregada etiqueta "shippable" a product.
Agregada etiqueta "available" para hacer borrados lógicos.
Agregada "state" a direcciones.
Corregido tipo de datos "quantity", "number".
Agregada "surname", "phone" a user, añadida collecion "admin".
Diseño: [aqui](https://github.com/IntersysConsulting/ingangsters-api/wiki/Database)
