### ISSUE TITLE
Python image compression

### ISSUE THREAD

**Issue by jogadev** [IntersysConsulting/ingangsters-api#16]
Investigate image compression libraries available for python 3.

**Comment by sofia-robles-Intersys** [comment]
`from PIL import Image

#Import Image
file = 'dog.jpg'

#Get Image properties
img_org = Image.open(file)
width_org, heigth_org = img_org.size

#Scale image
factor = 0.25
width = int(width_org * factor)
heigth = int(heigth_org * factor)
new_image = img_org.resize((width,heigth), Image.ANTIALIAS)

#Save Image
new_name = 'dogx25.jpg'
new_image.save(new_name)`
